-- 코드를 입력하세요
WITH BOOK_AND_AUTHOR AS (
    SELECT A.AUTHOR_NAME, B.CATEGORY, B.PRICE, B.BOOK_ID ,A.AUTHOR_ID
    FROM BOOK AS B JOIN AUTHOR AS A ON B.AUTHOR_ID = A.AUTHOR_ID
), BOOK_SALES_JAN AS (
    SELECT *
    FROM BOOK_SALES 
    WHERE YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 01
)

SELECT B.AUTHOR_ID, B.AUTHOR_NAME, B.CATEGORY, SUM(J.SALES*B.PRICE) AS TOTAL_SALES
FROM BOOK_AND_AUTHOR AS B JOIN BOOK_SALES_JAN AS J ON B.BOOK_ID = J.BOOK_ID
GROUP BY B.AUTHOR_ID, B.CATEGORY
ORDER BY B.AUTHOR_ID ASC, B.CATEGORY DESC