WITH FIND_CAR_WITH_DUR AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, C.OPTIONS
    FROM CAR_RENTAL_COMPANY_CAR  AS C 
    WHERE C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' 
        AND END_DATE >= '2022-11-01'
    ) AND C.CAR_TYPE IN ('세단', 'SUV')
)
SELECT DISTINCT D.CAR_ID, D.CAR_TYPE, FLOOR(D.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100)) AS FEE
FROM FIND_CAR_WITH_DUR AS D 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
    ON D.CAR_TYPE = P.CAR_TYPE
WHERE P.DURATION_TYPE = '30일 이상'
AND (D.DAILY_FEE * 30 * (1 - P.DISCOUNT_RATE/100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, D.CAR_TYPE ASC, D.CAR_ID DESC;