WITH ABLE_TO_RENT AS (
    SELECT C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, C.OPTIONS
    FROM CAR_RENTAL_COMPANY_CAR AS C
    WHERE C.CAR_ID NOT IN(
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' 
        AND END_DATE >= '2022-11-01'
    )
     AND C.CAR_TYPE IN ('세단', 'SUV')
)

SELECT R.CAR_ID, R.CAR_TYPE, ROUND((R.DAILY_FEE * 30)*(1 - P.DISCOUNT_RATE / 100), 0) AS FEE
FROM ABLE_TO_RENT AS R JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON R.CAR_TYPE = P.CAR_TYPE
WHERE P.CAR_TYPE != '트럭' AND DURATION_TYPE = '30일 이상'
HAVING FEE >=500000 AND FEE <2000000
ORDER BY FEE DESC, R.CAR_TYPE, R.CAR_ID DESC;