-- 코드를 입력하세요
WITH MF AS (
    SELECT MAX(FAVORITES) AS MF, FOOD_TYPE
    FROM REST_INFO 
    GROUP BY FOOD_TYPE
)
SELECT I.FOOD_TYPE, I.REST_ID, I.REST_NAME, I.FAVORITES
FROM REST_INFO I JOIN MF
ON I.FOOD_TYPE = MF.FOOD_TYPE AND MF.MF = I.FAVORITES
ORDER BY I.FOOD_TYPE DESC