-- 코드를 입력하세요
SELECT 
    U.USER_ID, 
    U.NICKNAME, 
    CONCAT(U.CITY,' ',STREET_ADDRESS1,' ',STREET_ADDRESS2) AS '전체주소', 
    CONCAT(LEFT(TLNO,3),'-',SUBSTRING(TLNO , 4, 4),'-',RIGHT(TLNO,4)) AS '전화번호'
FROM USED_GOODS_BOARD AS D JOIN USED_GOODS_USER AS U ON D.WRITER_ID = U.USER_ID
GROUP BY D. WRITER_ID
HAVING COUNT(D.WRITER_ID)>=3
ORDER BY U.USER_ID DESC;
