-- 코드를 입력하세요
WITH MALE AS (
    SELECT I.ANIMAL_ID, O.ANIMAL_TYPE, I.NAME 
    FROM ANIMAL_INS AS I JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID=O.ANIMAL_ID
    WHERE I.SEX_UPON_INTAKE='Intact Male' AND O.SEX_UPON_OUTCOME='Neutered Male'
), FEMALE AS(
    SELECT I.ANIMAL_ID, O.ANIMAL_TYPE, I.NAME 
    FROM ANIMAL_INS AS I JOIN ANIMAL_OUTS AS O ON I.ANIMAL_ID=O.ANIMAL_ID
    WHERE I.SEX_UPON_INTAKE='Intact Female' AND O.SEX_UPON_OUTCOME='Spayed Female'
)
SELECT *
FROM MALE
UNION
SELECT *
FROM FEMALE
ORDER BY ANIMAL_ID
