-- 코드를 입력하세요
WITH JOINED_2021 AS (
    SELECT USER_ID, GENDER, AGE, JOINED, COUNT(*) AS TOTAL_USERS
    FROM USER_INFO 
    WHERE YEAR(JOINED) = 2021
)
SELECT 
    YEAR(O.SALES_DATE) AS 'YEAR', 
    MONTH(O.SALES_DATE) AS 'MONTH', 
    COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT O.USER_ID) / J.TOTAL_USERS, 1) AS PURCHASED_RATIO
FROM ONLINE_SALE O
JOIN USER_INFO U ON O.USER_ID = U.USER_ID
CROSS JOIN JOINED_2021 AS J
WHERE YEAR(U.JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH;