WITH CNTCNTCNT AS (
    SELECT HOST_ID
    FROM PLACES 
    GROUP BY HOST_ID
    HAVING COUNT(HOST_ID)>=2
)
SELECT ID, NAME, HOST_ID
FROM PLACES 
WHERE HOST_ID IN (
    SELECT *
    FROM CNTCNTCNT
)
ORDER BY ID