WITH NOT_CANCLED_P AS (
    SELECT P.PT_NAME, P.PT_NO, A.APNT_NO, A.APNT_YMD, A.MDDR_ID AS DR_ID, A.MCDP_CD
    FROM PATIENT AS P JOIN APPOINTMENT AS A ON P.PT_NO = A.PT_NO
    WHERE A.APNT_CNCL_YN = 'N' AND A.MCDP_CD = 'CS' AND DATE_FORMAT(A.APNT_YMD, '%Y-%m-%d') = '2022-04-13'
)
SELECT P.APNT_NO, P.PT_NAME, P.PT_NO, P.MCDP_CD, D.DR_NAME, P.APNT_YMD
FROM NOT_CANCLED_P AS P JOIN DOCTOR AS D ON P.DR_ID = D.DR_ID
ORDER BY P.APNT_YMD

