-- 코드를 입력하세요
WITH REVIEW_COUNT 
AS (
    SELECT MEMBER_ID, COUNT(*) AS REVIEW_CNT 
    FROM REST_REVIEW 
    GROUP BY MEMBER_ID
)
SELECT P.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE AS P JOIN REST_REVIEW AS R
ON P.MEMBER_ID=R.MEMBER_ID
WHERE P.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REVIEW_COUNT
    WHERE REVIEW_CNT = (SELECT MAX(REVIEW_CNT) FROM REVIEW_COUNT)
)
ORDER BY r.REVIEW_DATE ASC, r.REVIEW_TEXT ASC;