-- 코드를 입력하세요
WITH MORE_THAN_5 AS (
    SELECT CAR_ID, COUNT(CAR_ID) AS CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) BETWEEN 8 AND 10
    GROUP BY CAR_ID
    HAVING CNT >= 5
)

SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(*) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE MONTH(START_DATE) BETWEEN 8 AND 10 AND CAR_ID IN (
    SELECT CAR_ID
    FROM MORE_THAN_5
)
GROUP BY MONTH, CAR_ID
ORDER BY MONTH, CAR_ID DESC;