-- 코드를 입력하세요
WITH NEW_HISTORY AS (
    SELECT *
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE MONTH(START_DATE) = 10
)

SELECT DISTINCT H.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR AS C JOIN NEW_HISTORY AS H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단'
ORDER BY H.CAR_ID DESC;
