-- 코드를 입력하세요
WITH MAX_PRICE AS(
    SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE
    FROM FOOD_PRODUCT 
    WHERE CATEGORY IN('과자', '국', '김치', '식용유')
    GROUP BY CATEGORY
)
SELECT F.CATEGORY, M.MAX_PRICE, F.PRODUCT_NAME
FROM FOOD_PRODUCT AS F JOIN MAX_PRICE AS M ON F.CATEGORY = M.CATEGORY AND F.PRICE = M.MAX_PRICE
ORDER BY M.MAX_PRICE DESC
